server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/infosys
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    allow-circular-references: true
  logging:
    level:
      org:
        springframework=DEBUG:

swagger.enabled: true